M/202407
k-arakawa-forspec/django_x pull request #18
Opened 2024-08-21 13:17 UTC by Haru-RS13

第2回（2024年7月度）研修 課題提出
1. 任意のユーザのプロフィール照会画面実装
2. ログインユーザのプロフィール照会画面実装
3. ログインユーザのプロフィール編集画面実装
4. User が create されるときに Profile も create されるよう実装する

1~4の課題が全て完成しているわけではないですが未提出を避けるために、
一旦未完成そのままにしてコミット/プルリクしました
この後も継続して課題を進めるため、追加でプルリクするかもしれません。

2024-09-06 07:34 UTC, Haru-RS13 commented
9/6(金)のプルリク内容
第2回（2024年7月度）研修 課題提出

完成(前回は側のみでデータの表示が部分的だった)
1. 任意のユーザのプロフィール照会画面実装
2. ログインユーザのプロフィール照会画面実装
3. ログインユーザのプロフィール編集画面実装

着手中
4. User が create されるときに Profile も create されるよう実装する

2024-09-09 09:12 UTC, Haru-RS13 commented
4. User が create されるときに Profile も create されるよう実装する

上記、shellにてProfilesを確認したところ、生成されていたため、
9/6(金)のプルリクにて完成していたようです。
9/6(金)にて、正式に提出とさせていただきます。

2024-09-09 10:26 UTC, k-arakawa-forspec requested changes

2024-09-09 10:26 UTC, k-arakawa-forspec commented on accounts/models.py
> +    Profile.objects.get_or_create(user=self)
余裕があれば `self._state.adding` を使った実装もよろしこ

2024-09-09 10:26 UTC, k-arakawa-forspec commented on profiles/urls.py
> +  path('<int:pk>/my/', views.MyProfView.as_view(), name="myprof"),
URL違うよ

2024-09-09 10:26 UTC, k-arakawa-forspec commented on profiles/views.py
> +class ProfileUpdateView(LoginRequiredMixin, UpdateView):
`LoginRequiredMixin` の継承はいらんよーｗ（2回目）

2024-09-09 10:26 UTC, k-arakawa-forspec commented on profiles/views.py
> +class ProfileUpdateView(LoginRequiredMixin, UpdateView):
ProfileUpdateView() の実装ってこれで完了している？  
これでログインユーザのプロフィールの更新できてる？？  
※更新できる気がしないんだけど。

2024-09-09 10:26 UTC, k-arakawa-forspec commented on templates/profiles/myprof.html
> +            <a />プロフィールを編集する</a>
hrefないの？

2024-09-11 02:42 UTC, Haru-RS13 commented on profiles/views.py
> +class ProfileUpdateView(LoginRequiredMixin, UpdateView):
こちら失礼しました。
直前にCtrl＋Zで戻してそのままのデータであげてました。
11:30過ぎに再度あげておりますので、ご確認いただけたらと思います。

2024-09-11 02:44 UTC, Haru-RS13 commented on accounts/models.py
> +    Profile.objects.get_or_create(user=self)
下記URLの修正で時間使い潰しそうそうなので、明日までにあげられなさそうです。それ以降でも大丈夫であれば、上記実装にチャレンジします。

2024-09-12 11:40 UTC, Haru-RS13 commented on profiles/urls.py
> +  path('<int:pk>/my/', views.MyProfView.as_view(), name="myprof"),
上記指定されている通りに修正しました。

2024-09-12 11:41 UTC, Haru-RS13 commented on templates/profiles/myprof.html
> +            <a />プロフィールを編集する</a>
上記修正しました。

2024-09-12 12:24 UTC, Haru-RS13 commented on profiles/views.py
> +class ProfileUpdateView(LoginRequiredMixin, UpdateView):
Updateに関する部分修正とurl.pyとhtmlに微調整加えました。

2024-09-13 03:21 UTC, k-arakawa-forspec commented on templates/profiles/myprof.html
> +    </div>
https://github.com/k-arakawa-forspec/django_x/wiki/%E7%AC%AC2%E5%9B%9E%EF%BC%882024%E5%B9%B47%E6%9C%88%E5%BA%A6%EF%BC%89%E7%A0%94%E4%BF%AE#template

>ログインユーザのプロフィール照会画面上には編集画面へのリンクを設ける。 
>また、Template は できれば 「任意のユーザのプロフィール照会画面」と共通ファイルとする。 
>つまり Template は「ログインユーザのプロフィール照会」時にのみ編集画面へのリンクが表示されるように実装する。

prof.html と myprof.html を1ファイルに統合して、編集するリンクの表示/非表示が制御できればベターだね

2024-09-13 03:37 UTC, Haru-RS13 commented on templates/profiles/myprof.html
> +    </div>
共有の指定、見逃してました。失礼しました。

2024-09-13 07:30 UTC, k-arakawa-forspec commented on templates/profiles/myprof.html
> +    </div>
余裕があればトライしてみる、でいいよー

>htmlの切り替え部分に関する箇所の実装を提出しておりますが....。

提出している？
誤字かな？ｗ

2024-09-13 08:42 UTC, Haru-RS13 commented on templates/profiles/myprof.html
> +    </div>
すみません、誤字です。
2~3日前の提出でも大丈夫ならってことを書こうとして気づかずにコメント確定させた感じですね。

2024-10-11 06:08 UTC, closed without merging