m/202411 課題 須藤
k-arakawa-forspec/django_x pull request #41
Opened 2024-12-11 12:38 UTC by Haru-RS13

できてるとこまでの提出です。
いくつかのサイトをまたいで見様見真似の記載のため良くない箇所あるかもしれないです。
また、X(旧：Twitter)のようにカンマなどの表示は対応してません。
現状(12/11)としては、カウントした値を画面に表示する直前？のところで上手くいってません。
1か所2か所直せば表示できそうな予感はしてますが期間内に完成まで持っていける自信は正直無い。
勉強会当日までできる限り課題に取り組み、完成に近づけます(できたら完成させます)。

2024-12-11 16:50 UTC, k-arakawa-forspec requested changes
取り急ぎ明らかにおかしそうな部分だけコメントしました

2024-12-11 16:50 UTC, k-arakawa-forspec commented on templates/users/detail.html
> +                    <button type="submit" class="btn btn-outline-primary">フォロー</button>
なんでココを編集したんだろう・・・

2024-12-11 16:50 UTC, k-arakawa-forspec commented on templates/users/detail.html
> +               <h6>{{ user.following }}<p>フォロー中</p></h6>
Userクラスにfollowingなんて属性ないはすだからエラーになる気がする。

https://github.com/k-arakawa-forspec/django_x/blob/7bcd60fbb3e9f5fa188ad3925bd3780472dcbdda/users/views.py#L28  
↑までできていて、`context['following']` を設定しているのだから・・・？

2024-12-11 16:50 UTC, k-arakawa-forspec commented on users/views.py
> +class followingView(DetailView):
クラス名は先頭大文字にすべきだね

2024-12-11 16:50 UTC, k-arakawa-forspec commented on users/views.py
> +    context['following'] = self.object.follow_user_set.all().select_related('profile')
この `followingView` class 内の処理を見る限り `self.object` がエラーになりそうな気がするけど、どう？  

`self.object` に期待しているものって  
「usersテーブルのレコードの内、login_id カラムの値が URL中の login_id に等しいレコードのUserオブジェクト」  
だと思うんだけど `followingView` class内に↑の指定が一切出てこないので  
期待するものが取れるはずがないんだよね。  
`ProifileDetail` classとよく見比べてみて。

2024-12-12 00:22 UTC, Haru-RS13 commented
ありがとうございます。各所確認して修正します。

2024-12-12 00:24 UTC, Haru-RS13 commented on templates/users/detail.html
> +                    <button type="submit" class="btn btn-outline-primary">フォロー</button>
覚えてませんが、フォロー中を打たずコピペした時に中の字が消えてしまったのかもしれません。

2024-12-12 13:21 UTC, k-arakawa-forspec requested changes

2024-12-12 13:21 UTC, k-arakawa-forspec commented on templates/users/following.html
> +            {% include "users/partials/user.html" %}
まずは共通テンプレートに切り出さず、この following.html で完結する書き方にしてみたら？  
それで表示に問題がないところまでいったら、共通テンプレートに切り出してみる。

2024-12-19 10:58 UTC, closed without merging